### ISSUE TITLE
autobank problem

### ISSUE THREAD

**Issue by SelvinPL** [ssjason123/SDCC_VS#1]
When using autobanks I've got an error:

>D:\gb\gbdk\bin\makebin.exe -Z -ya 4 -yt 27 -yn "Project" -yc "D:\gb\projects\Project\Debug\Project.ihx" "D:\gb\projects\Project\Debug\Project.gb"
>SDCCMAKEBIN : error : size of the buffer is too small.

When I do:
>D:\gb\gbdk\bin\makebin.exe -Z -yo A -ya 4 -yt 27 -yn "Project" -yc "D:\gb\projects\Project\Debug\Project.ihx" "D:\gb\projects\Project\Debug\Project.gb"

from command line project does compile

Unfortunately I cannot set -yo to A as 
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\SDCC\SDCC.Common.targets(683,18): error MSB4030: "A" is an invalid value for the "GameBoyRomBankCount" parameter of the "SDCCMakeBin" task. The "GameBoyRomBankCount" parameter is of type "System.Int32".
while A is valid parameter for -yo

Could you change from int to string or add option for autobanking?

**Comment by ssjason123** [comment]
Sure thing. Let me take a look at the latest makebin and see if there is similar option for the ram banks.

**Comment by ssjason123** [comment]
New release is up. Let me know if that works. I also added some other new gameboy makebin options that were missing.

**Comment by SelvinPL** [comment]
perfect, thnx
